In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Assuming the file is in the root of 'My Drive'
url="/content/titanic.csv"
dataset=pd.read_csv(url) # Use read_excel for .xlsx files
url3="/content/Countries.csv"
cnt=pd.read_csv(url3)
url2='/content/anime.csv'
an=pd.read_csv(url2)
url4 = '/content/mymoviedb.csv'
mo = pd.read_csv(url4, lineterminator='\n')

In [ ]:
data={
  'name':[np.nan,'monir','masum'],
  'age':[2,23,45]
}
df=pd.DataFrame(data)
print(df)

    name  age
0    NaN    2
1  monir   23
2  masum   45

In [ ]:
df[['age','name']]

   age   name
0    2    NaN
1   23  monir
2   45  masum

In [ ]:
df['salary']=[2,3,4]
df

    name  age  salary
0    NaN    2       2
1  monir   23       3
2  masum   45       4

In [ ]:
#df.drop('name',inplace=True,axis=1)
df

    name  age  salary
0    NaN    2       2
1  monir   23       3
2  masum   45       4

In [ ]:
df

    name  age  salary
0    NaN    2       2
1  monir   23       3
2  masum   45       4

In [ ]:
df.loc[[0,1]][['age','salary']] # for specific zone

   age  salary
0    2       2
1   23       3

In [ ]:
df[(df['age']>5) & (df['salary']>2)] # condtion for age print the columns , here can i use one condition and aslo two here i have use two condtion for understand and for reserv

    name  age  salary
1  monir   23       3
2  masum   45       4

In [ ]:
df.isnull().sum() # check for missing value

name      1
age       0
salary    0
dtype: int64

In [ ]:
df.dropna(thresh=0) # remove row in there is any null value

    name  age  salary
0    NaN    2       2
1  monir   23       3
2  masum   45       4

In [ ]:
#df.fillna(df['age'].df['age'].mean())
# for merge , df.merge(fist data,second data)

In [ ]:
#df2.join(df1)

In [ ]:
da1= {
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, None, 40]
}
data1=pd.DataFrame(da1)
da2 = {
    'ID': [3, 4, 5],
    'City': ['New York', None, 'Los Angeles'],
    'Salary': [70000, 80000, None]
}
data2=pd.DataFrame(da2)

In [ ]:
data1

   ID     Name   Age
0   1    Alice  25.0
1   2      Bob  30.0
2   3  Charlie   NaN
3   4    David  40.0

In [ ]:
data2

   ID         City   Salary
0   3     New York  70000.0
1   4         None  80000.0
2   5  Los Angeles      NaN

In [ ]:
pd.merge(data1,data2,on='ID', how="inner")# on = common term, on na dile defaul niye kal kore,
# r common term na thakle no a dile error dibe jemon here name is not common

# r how='inner' , common ID er majheo common number niye kaj kore r inner na dewa thake
# deful value hisebe ja common thake ta niye e kaj kore
# if i put here outer then just concider the column name

   ID     Name   Age      City   Salary
0   3  Charlie   NaN  New York  70000.0
1   4    David  40.0      None  80000.0

In [ ]:
pd.merge(data1,data2,on='ID', how="outer")

   ID     Name   Age         City   Salary
0   1    Alice  25.0          NaN      NaN
1   2      Bob  30.0          NaN      NaN
2   3  Charlie   NaN     New York  70000.0
3   4    David  40.0         None  80000.0
4   5      NaN   NaN  Los Angeles      NaN

In [ ]:
# if i put at how=left or right then it's merge base serial here data1=left, data2=right
pd.merge(data1,data2, how='left',on='ID')

   ID     Name   Age      City   Salary
0   1    Alice  25.0       NaN      NaN
1   2      Bob  30.0       NaN      NaN
2   3  Charlie   NaN  New York  70000.0
3   4    David  40.0      None  80000.0

In [ ]:
pd.concat([data1,data2]) # if here i put axis=1 then it base on column

   ID     Name   Age         City   Salary
0   1    Alice  25.0          NaN      NaN
1   2      Bob  30.0          NaN      NaN
2   3  Charlie   NaN          NaN      NaN
3   4    David  40.0          NaN      NaN
0   3      NaN   NaN     New York  70000.0
1   4      NaN   NaN         None  80000.0
2   5      NaN   NaN  Los Angeles      NaN

In [ ]:
# join is almot like merge but if here common column then wou't work
#data1.join(data2,how='inner')

In [ ]:
da3 = {
    'Department': ['a', 'a', 'a', 'b', 'b', 'a', 'b'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 75000, 62000],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F']
}
data3=pd.DataFrame(da3)
data3

  Department Employee  Salary Gender
0          a    Alice   50000      F
1          a      Bob   55000      M
2          a  Charlie   60000      M
3          b    David   65000      M
4          b      Eve   70000      F
5          a    Frank   75000      M
6          b    Grace   62000      F

In [ ]:
cat=data3.groupby("Department")

In [ ]:
for i,j in cat:
  print(i)
  print(j)

a
  Department Employee  Salary Gender
0          a    Alice   50000      F
1          a      Bob   55000      M
2          a  Charlie   60000      M
5          a    Frank   75000      M
b
  Department Employee  Salary Gender
3          b    David   65000      M
4          b      Eve   70000      F
6          b    Grace   62000      F

In [ ]:
data3.groupby("Department")['Salary'].sum()

Department
a    240000
b    197000
Name: Salary, dtype: int64

In [ ]:
gen=data3.groupby('Gender')

In [ ]:
for i,j in gen:
  print(i)
  print(j)

F
  Department Employee  Salary Gender
0          a    Alice   50000      F
4          b      Eve   70000      F
6          b    Grace   62000      F
M
  Department Employee  Salary Gender
1          a      Bob   55000      M
2          a  Charlie   60000      M
3          b    David   65000      M
5          a    Frank   75000      M

In [ ]:
da4= {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['Apples', 'Apples', 'Apples', 'Apples', 'Oranges', 'Oranges', 'Oranges', 'Oranges'],
    'Month': ['Jan', 'Jan', 'Jan', 'Jan', 'Feb', 'Feb', 'Feb', 'Feb'],
    'Sales': [150, 200, 130, 170, 180, 220, 160, 190]
}
data4=pd.DataFrame(da4)
data4

  Region  Product Month  Sales
0  North   Apples   Jan    150
1  South   Apples   Jan    200
2   East   Apples   Jan    130
3   West   Apples   Jan    170
4  North  Oranges   Feb    180
5  South  Oranges   Feb    220
6   East  Oranges   Feb    160
7   West  Oranges   Feb    190

In [ ]:
pd.pivot_table(data4,values='Sales',index="Region",columns="Month",aggfunc='sum' )

Month   Feb  Jan
Region
East    160  130
North   180  150
South   220  200
West    190  170

In [ ]:
#pd.pivot_table(data4,values=['Sales','Product'],index="Region",columns="Month" )
# as a value i can just use numerical value

In [ ]:
dataset.shape

(891, 12)

In [ ]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
dataset.loc[[1,4,6],['Sex','Name']]

      Sex                                               Name
1  female  Cumings, Mrs. John Bradley (Florence Briggs Th...
4    male                           Allen, Mr. William Henry
6    male                            McCarthy, Mr. Timothy J

In [ ]:
dataset.loc[2]['Name']

'Heikkinen, Miss. Laina'

In [ ]:
def extra(txt):
  data=''
  check=False
  for i in txt:
      if i=='(':
        check=True
        continue # Start capturing after '('
      if i==')':
        check=False
        break # Stop capturing after ')'
      if check==True: # Only append if inside parentheses
          data=data+i
  return data

In [ ]:
ep=an['Title'].apply(extra)
an["episode"]=ep

In [ ]:
an.head()

   Rank                                              Title  Score episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10  64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07  24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06  13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06  51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05  10 eps

In [ ]:
an['episode']=an['episode'].str.replace(" eps",'')

In [ ]:
an.head()

   Rank                                              Title  Score episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10

In [ ]:
an['episode']=an['episode'].astype(int)

In [ ]:
an.head()

   Rank                                              Title  Score  episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [ ]:
an['Title']

0     Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1     Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2     Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3     Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4     Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
5     Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...
6     Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...
7     Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...
8     Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...
9     Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...
10    Shingeki no Kyojin: The Final Season - Kankets...
11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
12    Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...
13    Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...
14    Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...
15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
16    Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...
17    3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...
18    Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...
19    Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...
20    Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...
21    Violet Evergarden MovieMovie (1 eps)Sep 2020 -...
22    Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...
23    Gintama.: Shirogane no Tamashii-hen - Kouhan-s...
24    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...
25    Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...
26    Kaguya-sama wa Kokurasetai: First Kiss wa Owar...
27    Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...
28    The First Slam DunkMovie (1 eps)Dec 2022 - Dec...
29    Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...
30    Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...
31    Gintama.: Shirogane no Tamashii-henTV (12 eps)...
32    Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...
33    Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...
34    Shingeki no Kyojin: The Final SeasonTV (16 eps...
35    Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...
36    Kizumonogatari III: Reiketsu-henMovie (1 eps)J...
37    "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...
38    Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...
39    Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...
40    Monogatari Series: Second SeasonTV (26 eps)Jul...
41    Shingeki no Kyojin: The Final Season Part 2TV ...
42    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...
43    Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...
44    Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...
45    Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...
46    Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...
47    Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...
48    Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...
49    Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...
Name: Title, dtype: object

In [ ]:
cnt.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [ ]:
cnt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [ ]:
cnt.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [ ]:
cnt.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [ ]:
m=cnt['population'].idxmax()
m

75

In [ ]:
print(cnt.loc[m]["population"])

1417173173

In [ ]:
cnt['population'].idxmin()

179

In [ ]:
cnt.loc[cnt['population'].idxmin()]

country                        Tuvalu
country_long                   Tuvalu
currency            Australian dollar
capital_city                 Funafuti
region                      Polynesia
                          ...
democracy_score                   0.0
democracy_type                Unknown
median_age                       21.0
political_leader        Kausea Natano
title                  Prime Minister
Name: 179, Length: 64, dtype: object

In [ ]:
cnt.loc[179][['capital_city','population']]

capital_city    Funafuti
population         11312
Name: 179, dtype: object

In [ ]:
cnt['region'].value_counts(dropna=False).sum()

np.int64(194)

In [ ]:
t=cnt['region'].unique()
len(t)

22

In [ ]:
cnt['region'].nunique()

22

In [ ]:
cnt['democracy_score'].max()

9.87

In [ ]:
cnt['democracy_score'].nlargest(5)

127    9.87
74     9.58
164    9.39
122    9.26
46     9.22
Name: democracy_score, dtype: float64

In [ ]:
cnt.sort_values(by='democracy_score',ascending=False).head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.0,10.0,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.0,-18.0,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.0,15.0,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.0,174.0,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.0,10.0,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister

In [ ]:
cnt[cnt['region']=='Southern Europe']['country']

1                     Albania
3                     Andorra
20     Bosnia and Herzegovina
40                    Croatia
42                     Cyprus
65                     Greece
81                      Italy
105                     Malta
114                Montenegro
126           North Macedonia
137                  Portugal
143                San Marino
147                    Serbia
152                  Slovenia
157                     Spain
Name: country, dtype: object

In [ ]:
mo.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [ ]:
mo["Popularity"].idxmax()

0

In [ ]:
mo.loc[0][['Title','Genre']]

Title               Spider-Man: No Way Home
Genre    Action, Adventure, Science Fiction
Name: 0, dtype: object

In [ ]:
mo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   object
 1   Title              9827 non-null   object
 2   Overview           9827 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   object
 7   Genre              9827 non-null   object
 8   Poster_Url         9827 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 691.1+ KB

In [ ]:
mo.describe()

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9827.000000   9827.000000
mean     40.326088   1392.805536      6.439534
std     108.873998   2611.206907      1.129759
min      13.354000      0.000000      0.000000
25%      16.128500    146.000000      5.900000
50%      21.199000    444.000000      6.500000
75%      35.191500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

In [ ]:
mo.duplicated().sum()

np.int64(0)

In [ ]:
mo.drop('Original_Language', axis=1).head(1)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...

In [ ]:
mo.head(1)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...

In [ ]:
mo.drop(['Overview','Original_Language','Poster_Url'],axis=1).head(1)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"

In [ ]:
mo.describe().max()

Popularity       9827.0
Vote_Count      31077.0
Vote_Average     9827.0
dtype: float64

In [ ]:
des=mo['Vote_Count'].describe()

bins=[des['min'],des['25%'],des['50%'],des['75%'],des['max']]
labels=['low','below_avarage','avarage','popular']
mo['category']=pd.cut(mo['Vote_Count'],bins=bins,labels=labels,include_lowest=True)
mo.head(2)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,category
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,popular
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,avarage

In [ ]:
mo['category2']=pd.qcut(mo['Vote_Count'],q=4,labels=['low','below average','average','popular'])
mo.head(2)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url,category,category2
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...,popular,popular
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...,avarage,average

In [ ]:
mo=mo.drop(mo[['Overview','Original_Language','Poster_Url']],axis=1)

In [ ]:
mo.head(2)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,category,category2
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",popular,popular
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller",avarage,average

In [ ]:
mo['category'].value_counts()

category
low              2461
popular          2456
below_avarage    2455
avarage          2455
Name: count, dtype: int64

In [ ]:
mo.nunique()

Release_Date    5893
Title           9513
Popularity      8160
Vote_Count      3266
Vote_Average      74
Genre           2337
category           4
category2          4
dtype: int64

In [ ]:

mo=mo.explode('Genre').reset_index(drop=True)
mo.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,category,category2
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",popular,popular
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller",avarage,average
2,2022-02-25,No Exit,2618.087,122,6.3,Thriller,low,low
3,2021-11-24,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy",popular,popular
4,2021-12-22,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War",popular,popular

In [ ]:
an.head()

   Rank                                              Title  Score  episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [ ]:
dataset.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [ ]:
mo.head(1)

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre,category,category2
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction",popular,popular

In [ ]:
cnt.head(1)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.0161,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President

In [ ]:
cnt.columns.value_counts().sum()

np.int64(64)

In [ ]:
cnt['population'].idxmax()

75

In [ ]:
cnt.loc[75]

country                         India
country_long        Republic of India
currency                 Indian rupee
capital_city                New Delhi
region                  Southern Asia
                          ...
democracy_score                  7.23
democracy_type       Flawed democracy
median_age                       23.9
political_leader        Narendra Modi
title                  Prime Minister
Name: 75, Length: 64, dtype: object